#!/bin/sh

RDIR="`echo "$1" | sed -e 's/\/[^\/]*$//g' | sed -e 's/^\.\///g'`/"
if test "x$1" = "x"
then
	RDIR="./"
fi
shift
if test ! -d "${RDIR}"
then
	echo "Error: Directory of the repository not found."
	exit 1
fi

# you can use all git status options
# what kind of changes show be shown by git? see git-status option -u
# default: no - Show no untracked files

if test "x${RDIR}" != "x"
then
	if test "x${GIT_DIR}" != "x" && test "x${GIT_DIR}" != "x.git"
	then
		echo "[01m[34mGIT2: $RDIR[0m"
	else
		echo "[01m[34mGIT: $RDIR[0m"
	fi

	cd "${RDIR}"
fi

git remote update >/dev/null

BASE=$(git merge-base @ @{u} 2>/dev/null)
if test "x$BASE" = "x"
then
	BASE="@"
fi

NUM=`git rev-list $BASE...@{u} --count 2>/dev/null`
LNUM=`git rev-list $BASE...@ --count`

if test "x$NUM" != "x" && test $NUM != 0
then
	echo "[01m[31mNeed to pull ($NUM commits behind)[0m"
fi
if test "x$LNUM" != "x" && test $LNUM != 0
then
	echo "[01m[31mNeed to push ($LNUM commits ahead)[0m"
fi

git status -s -uno $@ 

